Add scroll feature
viivue/frontend-debug pull request #8
Opened 2022-10-13 09:20 UTC by vuquangpham

2022-10-18 08:02 UTC, vuquangpham commented
I have finished this feature. Please check it again! Thanks.

2022-10-18 09:36 UTC, phucbm commented
We need to be able to control the scrolling speed. The best speed would be the number where visitors can read the content while the page is automatically scrolling to the bottom.

You can find a speed that you feel comfortable with, then calculate the average scrolling speed based on document height and this comfortable speed.

2022-10-18 09:36 UTC, phucbm requested changes
Scrolling at a readable speed.

2022-10-19 02:51 UTC, phucbm approved these changes

2022-10-19 02:51 UTC, merged